# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='comment_count',
        ),
    ]
